version: '3.9'
services:
  prod_frontend:
    container_name: hsl_frontend
    image: ghcr.io/alari777/project-hsl-citybike-app/project-hsl-citybike-app:latest
    ports:
      - "80:3000"
    links:
      - db
    depends_on:
      - db
    command: sh -c "npx prisma generate && npx prisma db push && npm start"
    networks:
      - hsln
  db:
    image: mysql:5.7.22
    container_name: dbmysql
    restart: always
    environment:
      MYSQL_DATABASE: hsl
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command:
      - /bin-sh
      - -c
      - |
        --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
        --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    networks:
      - hsln
networks:
  hsln:
    driver: bridge
