version: '3.9'
services:
  dev_frontend:
    container_name: hsl_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - db
  db:
    image: mysql:5.7.22
    container_name: dbmysql
    restart: always
    environment:
      MYSQL_DATABASE: hsl
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: >
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
      && /bin/sh -c "import-data.sh"
