import Head from 'next/head';
import { FC } from 'react';

type TripType = {
  id: number;
  departureDate: string;
  coveredDistance: string;
  duration: string;
  returnDate: string;
  departureStationId?: number;
  returnStationId?: number;
  departureStation: { nameFi: string };
  Stations_Trips_returnStationIdToStations: { nameFi: string };
};

interface ManagePageProps {
  trips: TripType[];
}

const HomePage: FC = () => {
  return (
    <>
      <Head>
        <title>City Bike app</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main className='main'>
        <div>Hello world!</div>
      </main>
    </>
  );
};

export default HomePage;
